version: "2"

services:
  node-api-sequelize:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    # command: ["npm", "run", "migrate"]
    networks:
      - default
      # - logapi_default
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "crud_sequelize"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
# networks:
#   logapi_default:
#     external: true
